# Generated by Django 4.1.7 on 2023-04-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_img',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
