# Generated by Django 4.1.7 on 2023-04-03 19:46

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_post_cover_img_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
