# Generated by Django 4.1.7 on 2023-04-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_like_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
