# Generated by Django 4.1.7 on 2023-05-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_post_topic'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique-owner-title'),
        ),
    ]
