# Generated by Django 4.1.7 on 2023-05-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique-owner-title',
        ),
    ]
